# Site settings
title: Gavin's Notes
description: >

author: Gavin Xu
email: i@gavln.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.gavln.com" # the base hostname & protocol for your site
twitter_username: hybrid_alex
github_username:  alexcarpenter

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:title
sass:
    style: compressed
